name: Docker

on:
  push

jobs:
  buildx:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: [3.9]
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup - buildx
      uses: docker/setup-buildx-action@v1

    - name: Setup - Github Container Registry
      uses: docker/login-action@v1
      if: ${{ steps.config.outputs.push-to-registry }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup - Dockerhub Container Registry
      uses: docker/login-action@v1
      if: ${{ steps.config.outputs.push-to-registry }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup - Docker image metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ github.repository }}
          a901002666/cloudflared
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=sha
          type=raw,value=latest

    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ steps.config.outputs.push-to-registry == 'true' }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
